### ISSUE TITLE
how to install the module without it installing apache...

### ISSUE THREAD

**Issue by bobweston** [example42/puppi#114]
I would like to use this module to install php on our production servers.

We're an nginx shop and don't use apache.

But I can't seem to get this module working without it installing apache. (which then leads to port conflicts on port 80).

Can someone tell me if it is possible to install this application without it installing apache? I really appreciate any help you can provide. My manifest is below:

class projects::interact::servers::app::php {
  include puppi
  ::php::module { "cli": }
  ::php::module { "fpm": }
  ::php::module { "mysql": }
  ::php::module { "ldap": }
  ::php::module { "imagick": }
  ::php::module { "curl": }
  ::php::module { "gd": }
  ::php::module { "json": }
  ::php::module { "mysqlnd": }
  ::php::module { "odbc": }
  ::php::module { "pgsql": }
  ::php::module { "snmp": }
  ::php::module { "tidy": }
  ::php::module { "xsl": }

  class { '::php':
    service => 'nginx',
    version => '5.3.10-1ubuntu3.15',
    require => Class['puppi'],
  }

}

**Comment by alvagante** [comment]
This is not an issue with puppi (do you use the puppi command? if not you don't need to include the puppi class) but with the php module. Which needs refactoring to work well with nginx.

**Comment by bobweston** [comment]
Yep. sorry. My mistake. I posted to the wrong repo.
My apologies.
