### ISSUE TITLE
Missing closing quotes in /files/scripts/report_mongo.sh

### ISSUE THREAD

**Issue by erikanderson** [example42/puppi#130]
Line 58 is missing a closing double quote: 

`if [ -z "${environment} ]`

It should be: 

`if [ -z "${environment}" ]`

**Comment by erikanderson** [comment]
Made PR: https://github.com/example42/puppi/pull/131

**Comment by alvagante** [comment]
ty,

**Comment by erikanderson** [comment]
Thanks for all the work you have put into these modules
