### ISSUE TITLE
Error while evaluating a Function Call, undefined method `scope_param'

### ISSUE THREAD

**Issue by vitxd** [example42/puppi#136]
Hello,
it's probably not a bug but I really can't figure out what's going on here.

I'm trying to use your PHP puppet library which uses params_lookup from this library. This is calling a function called scope_param which apparently is undefined. I don't know much about ruby so I don't know if it's a missing dependency or I'm doing something wrong. Can you please solve this mystery of mine? I would much appreciate

Thanks!

**Comment by alvagante** [comment]
Are you using the latest version of rhe puppi module? On which OS / Puppet version? Can you provide more details?

**Comment by vitxd** [comment]
Hello!
Yes, I just deleted and cloned the puppi module from github. I'm running puppet version 3.6.2 on a Centos7 linux server. Version of ruby is 2.0.0p598.

I think is probably something I've done wrong as I started writing my puppet script using Puphpet as a template, but I really cannot figure out what!

Let me know if you need any other details.

**Comment by alvagante** [comment]
Whst's the complete error message? Also can you include your code that uses the php module?
Incidentally, puppi functions is params_lookup, I'm not sure from where this scope_params comes out.

**Comment by vitxd** [comment]
this is the error:
`    default: Running: /var/folders/fv/vk9q1y054jl2p1r_fpc932940000gn/T/vagrant-shell20160404-55906-1nybigk
==> default: Running provisioner: puppet...
==> default: Running Puppet with ...
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/composer/lib/facter/composer_home.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/git/lib/facter/git_exec_path.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/git/lib/facter/git_html_path.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/git/lib/facter/git_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/php/lib/facter/php_fact_extension_dir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/php/lib/facter/php_fact_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/puppi/lib/facter/last_run.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/puppi/lib/facter/puppi_projects.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/puppi/lib/facter/windows_common_appdata.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/stdlib/lib/facter/facter_dot_d.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/stdlib/lib/facter/package_provider.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/stdlib/lib/facter/pe_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/stdlib/lib/facter/puppet_vardir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/stdlib/lib/facter/root_home.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/stdlib/lib/facter/service_provider.rb
==> default: Error: Evaluation Error: Error while evaluating a Function Call, undefined method `scope_param' for #<Puppet::Functions::InternalDispatchBuilder:0x00000004da9c20> at /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/php/manifests/init.pp:153:26 on node test-vm.kobas.dev
==> default: Error: Evaluation Error: Error while evaluating a Function Call, undefined method `scope_param' for #<Puppet::Functions::InternalDispatchBuilder:0x00000004da9c20> at /tmp/vagrant-puppet/modules-afaee76a50488a8c52b9d33d7ca3018d/php/manifests/init.pp:153:26 on node test-vm.kobas.dev
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

searching in the code for the word `scope_param` you can find it at line 18 of params_lookup.rb in the puppi module which is the function called at line 153 in init.pp on the php module

**Comment by alvagante** [comment]
This is strange, scope_params is in the version of params_lookuo which uses Puppet 4 functions api, it's not supposed to be loaded in Puppet 3. Do you have the future parser option enabled by chance?
I would try these steps in any case:
- remove lib/puppet/functions/params_lookup.rb from your local puppi directory , to be sure to use the puppet 3 compliant lib/puppet/parser/functions/params_lookup.rb
- if possible update your puppet to the latest 3.x version it should not have any compatibility issues

**Comment by vitxd** [comment]
yes! I fixed it upgrading the version of puppet and dropping the future parser! thank you very much for your help and patience!
