### ISSUE TITLE
Write Permissions on Files needed

### ISSUE THREAD

**Issue by rgarrow** [example42/puppi#137]
When we are publishing with in puppet we get a error on these following files. We only have read permission and Write permission is needed but it has to be done from the app not from our side.

total 80
-rw-r--r--. 1 leburges leburges  8889 Mar 30 10:27 checksums.json
-rw-r--r--. 1 leburges leburges   351 Aug  7  2015 composer.json
drwxr--r--. 5 leburges leburges    70 May  2 09:33 files
-rw-r--r--. 1 leburges leburges   502 Aug  7  2015 Gemfile
drwxr--r--. 4 leburges leburges    32 May  2 09:33 lib
-rw-r--r--. 1 leburges leburges   674 Aug  7  2015 LICENSE
drwxr--r--. 5 leburges leburges  4096 May  2 09:33 manifests
-rw-r--r--. 1 leburges leburges   615 Mar 30 10:27 metadata.json
-rw-r--r--. 1 leburges leburges   281 Aug  7  2015 Rakefile
-rw-r--r--. 1 leburges leburges  2599 Aug  7  2015 README_check.md
-rw-r--r--. 1 leburges leburges 14435 Aug  7  2015 README_deploy.md
-rw-r--r--. 1 leburges leburges  2700 Aug  7  2015 README_info.md
-rw-r--r--. 1 leburges leburges  1362 Aug  7  2015 README_log.md
-rw-r--r--. 1 leburges leburges  9852 Oct 19  2015 README.md
drwxr--r--. 5 leburges leburges    71 May  2 09:33 spec
drwxr--r--. 5 leburges leburges  4096 Mar 30 10:27 templates

**Comment by alvagante** [comment]
This should be fixed with version 2.1.14 from the forge (just uploaded)

**Comment by alvagante** [comment]
Actually probable also version 2.1.13 was fixed. You should have write permissions for the owner of the files.

**Comment by rgarrow** [comment]
Thank you very much for the quick response and solution to the issue. Greatly appreciated.
