### ISSUE TITLE
any2bool function now available in stdlib

### ISSUE THREAD

**Issue by nibalizer** [example42/puppi#138]
With https://github.com/puppetlabs/puppetlabs-stdlib/pull/601 landed, stdlib's next release will have an any2bool function. This will be conflicting with puppi, I suggest pinning latest stdlib in the next puppi release and removing the any2bool function.

**Comment by alvagante** [comment]
Thanks for the notice, will do that.

**Comment by kujeger** [comment]
Hi, is this still in the works?

**Comment by alvagante** [comment]
any2bool has been removed from puppi:
https://github.com/example42/puppi/commit/db0aac5ce2fd3d031011e09de6d74ac897a01222
Newer version pushed to the forge
