### ISSUE TITLE
Tag missing for 2.2.0 and 2.2.1

### ISSUE THREAD

**Issue by dol** [example42/puppi#146]
The Git tags for 2.2.0 and 2.2.1 are missing. I use this tags to compare the changes between the versions before updating the dependency.

**Comment by alvagante** [comment]
Sorry, those releases weren't automated. Would you be good for you to have a new release/tag on the current master and compare on that new one?

**Comment by dol** [comment]
I use this GitHub feature to compare tag/releases: https://github.com/example42/puppi/compare/v2.1.12...v2.1.13

> Would you be good for you to have a new release/tag on the current master and compare on that new one?
¯\_(ツ)_/¯, sorry. I'm not sure I fully understand your question. I hope my use case helps to find the correct solution.

**Comment by alvagante** [comment]
What I mean, is if is enough for you to have a new tag 2.2.2 pushed both to the forge on on git based on current master.

**Comment by alvagante** [comment]
A new tag, v2.2.2 has been published, here and on the forge
