### ISSUE TITLE
Puppet5 compatibility

### ISSUE THREAD

**Issue by FrankVanDamme** [example42/puppi#150]
Using the params_lookup function on Puppet version 5.0.0 is failing. 

Client error: 
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, undefined method `namespaces' for Scope(Class[Php]):Puppet::Parser::Scope at /etc/puppetlabs/code/... on node park

It looks like the core on line 59 in modules/puppi/lib/puppet/functions/params_lookup.rb is broken by the upgrade:
`  classname = scope.namespaces.first`

other than that, params_lookup still works; I can replace that method with an empty string with no functional impact.

**Comment by alvagante** [comment]
If you have a shareable fix for params_lookup on puppet 5, please share.

**Comment by alvagante** [comment]
Linked commit fixes the issue. I should have done this way before, sorry for delay.

**Comment by sathieu** [comment]
FYI this breaks `apt::dater` (which wants `apt::dater::params`)

**Comment by alvagante** [comment]
@sathieu thanks for reporting. 
I suppose is quicker to remove params_lookup from apt::dater and use normal params pattern or local defaults.
